### ISSUE TITLE
Pact files from Broker are not getting loaded up in Stub Server

### ISSUE THREAD

**Issue by vini46** [pact-foundation/pact-stub-server#13]
Pact files from Broker are not getting loaded up in Stub Server when using the -u, --url and passing the pact file Endpoint URL from a Pact Broker

URL format: http://<broker-url>/pacts/provider/<provider-name>/consumer/<consumer-name>/<version>

Expected Result:
Pact files should be loaded

Actual Result:
Error is thrown saying cannot load pact files

<img width="1141" alt="screen shot 2018-08-14 at 4 40 16 pm" src="https://user-images.githubusercontent.com/5517009/44190328-d8fadc80-a143-11e8-848f-fb2e603d2773.png">

**Comment by uglyog** [comment]
I've released version 0.1.0 with support for HTTPS

**Comment by minhdoan159** [comment]
Awesome! I have just get the pact-stub-service, i have a concern that if a Broker is set up with about 100 pact records, when i start stub-server with option --url/uri <Broker home url> whether all pact records are uploaded to server, or the option only works for each pact record, e.g: --url <Broker home url/provider/<ProviderName>/consumer/<ConsumerName>/latest>?
Hope this project grows as fast and many thanks for your contribution!

**Comment by uglyog** [comment]
At the moment, it will load a single pact file from the URL

**Comment by vini46** [comment]
Thank you @uglyog this is awesome 👍
