### ISSUE TITLE
adds content type header "application/javascript; charset=utf-8" to a matched pact's response

### ISSUE THREAD

**Issue by smckend** [pact-foundation/pact-stub-server#14]
I'm using this tool to test an application and found from the upgrade from version 0.0.10 to 0.1.0 breaks our tests.
After investigating, an exception was thrown due to the RestClient finding a content type of "application/javascript; charset=utf-8" in the response. After doing a verbose curl I could indeed see that the version 0.1.0 of the pact-stub-server adds this content type header along with any headers in the matched pact's response.

**Comment by uglyog** [comment]
I have released 0.1.1 with this fix
