### ISSUE TITLE
Issue while playing video and PUT request after :v0.0.9

### ISSUE THREAD

**Issue by Dolly2315** [pact-foundation/pact-stub-server#18]
So , I have pact file which successfully works till v0.0.9
But when i try to upgrade the version , pact file which contains

PUT request
file location for loading the video is failing
Please note : other pact files are working fine .
I cant see any logs getting published to it when it is upgraded version higher than v0.0.9
Logs : Attaching to flex-master
flex-master | 13:28:43 [INFO] Server started on port 30044
flex-search-app-flex-master.txt

Also console shows 200 response but no data under response
I have uploaded the json file which is generated after running the test
Please let me know if any further information is required

**Comment by uglyog** [comment]
This is probably related to #16

**Comment by uglyog** [comment]
Version 0.2.0 has been released
