### ISSUE TITLE
Date generator is not implemented

### ISSUE THREAD

**Issue by mstefan7** [pact-foundation/pact-stub-server#21]
Hi again, this is the second issue I'm facing. I have POST request that returns this in body: `{"birthDate": "1970-01-01"}`

while having this generator assigned `{"$.birthDate": {"type": "Date"}}`

On matched interaction, I get this message in logs: `[WARN] Date generator is not implemented`

Very same goes for generator of regex type. 
Can you please take a look?

**Comment by uglyog** [comment]
Date generators are still to be implemented in the upstream libraries (see https://github.com/pact-foundation/pact-reference/issues/33)

**Comment by uglyog** [comment]
Regex generators should be working. Can you provide the version you are using?

**Comment by uglyog** [comment]
Date and Regex generators have now been implemented in the upstream library. I can now create a new version to support this.
