### ISSUE TITLE
Does not implement pact's multi valued http response headers

### ISSUE THREAD

**Issue by mustakip** [pact-foundation/pact-stub-server#31]
It seems that multi valued headers are not supported yet. If v is an array then we have to repeat the header.
https://github.com/uglyog/pact-stub-server/blob/934b748809a5fa6fb45d22940e8d9595b43e0a34/src/pact_support.rs#L48

We faced the need of multi valued header while setting multiple cookies. 
https://github.com/DiUS/pact-jvm/issues/851

And the issue got fixed. The changes are done in https://github.com/DiUS/pact-jvm/commit/997e24ebdb2b5f420020480fcb607e1448d2da7b

**Comment by uglyog** [comment]
This needs a change to an upstream library. That will need to be released first.

**Comment by uglyog** [comment]
0.3.1 has been released with this fix
