### ISSUE TITLE
version `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by frastel** [pact-foundation/pact-stub-server#39]
I am trying to load the pact-stub-server as docker image.
However it does not work on both my Mac or on a Vagrant box.

System:
* OS X 10.15.7 + Docker Desktop with Docker Engine v20.10.0
* Vagrant Box Ubuntu 16.04.6+ Docker Engine 19.03.13

Command
```
docker run -ti -v "$(pwd)/artifacts/pacts/:/app/pact" pactfoundation/pact-stub-server -p 8080 -d pacts
```

exits with
```
./pact-stub-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./pact-stub-server)
```

**Comment by uglyog** [comment]
Are you using an Alpine-based docker image?

**Comment by uglyog** [comment]
Oh, no, you're using the pact foundation one. Let let look at what has changed there.

**Comment by frastel** [comment]
Yes exactly.
I decided to place the issue here because I think there is no other available binary which could be used within the mentioned docker image:
https://github.com/pact-foundation/pact-stub-server/blob/master/Dockerfile#L5

**Comment by uglyog** [comment]
I should prob merged these two repositories

**Comment by frastel** [comment]
... or provide the service within pactfoundation/pact-cli as it was already done with the pact-mock-service:
https://github.com/pact-foundation/pact-mock-service-docker.

**Comment by uglyog** [comment]
I've updated the release process to also create OSX and Windows binaries. You should be able to use the OSX one while I fix the docker image.

**Comment by uglyog** [comment]
I've re-created the docker image for v0.4.4. Can you try it again?

**Comment by rholshausen** [comment]
Latest version (0.5.2) supports glibc 2.18+
