### ISSUE TITLE
Provide a way to filter pacts fetched from Pact Broker

### ISSUE THREAD

**Issue by lmonkiewicz** [pact-foundation/pact-stub-server#46]
It is a more of feature request than issue ;)

I need a way to filter fetched pacts, using consumer name and/or provider name.

In my system, we are integrating with a third-party API that is serving multiple versions, and we have to support all of them, that means that we have consumer pacts defined for each version. Without such filtering mechanism, I'm unable to stub it correctly, ex. only single version of such API.

**Comment by rholshausen** [comment]
Released with version 0.5.0
