### ISSUE TITLE
Matching rules for arrays in query are not handled correctly

### ISSUE THREAD

**Issue by pdeszynski** [pact-foundation/pact-stub-server#48]
Having an interaction with a request like

```json
   "request": {
        "method": "GET",
        "path": "/endpoint/",
        "query": "ids=id&ids=id&ids=id",
        "matchingRules": {
          "$.query.ids": {
            "min": 2
          },
          "$.query.ids[*].*": {
            "match": "type"
          }
        }
      }
```

stub server will return 404 error when there's not an exact match for array length (so only request like `/endpoint?ids=id&ids=id` will be matched, but `/endpoint?ids=id&ids=id&ids=id` won't)

Expected behavior would be to return a response with minimum twice `ids` being defined. Tested on `pact-stub-server:0.5.0` and `pact-stub-server:v0.4.4`

**Comment by rholshausen** [comment]
0.5.1 has been released with the fix

**Comment by pdeszynski** [comment]
@rholshausen works like a charm, thanks!

**Comment by dheardal** [comment]
This seems to have regressed in 0.6.0
