### ISSUE TITLE
Regex support for provider-name and consumer-name

### ISSUE THREAD

**Issue by sann3** [pact-foundation/pact-stub-server#54]
Thanks for adding support for filtering the provider-name and consumer-name.  It will be helpful if we have support for using regex for provider-name and consumer-name.

Our use case is we have more than 10 provider-names, but all are having the same prefix, instead of repeating the provider-name 10 times, regex will be easy, also for future provider-name's no changes are required.

**Comment by YOU54F** [comment]
this is complete and available, documentation is updated to reflect
