### ISSUE TITLE
Failed to load pact file: Expected a "." or "[" instead of "'"  - happen after 0.4.4 version

### ISSUE THREAD

**Issue by CharlyApps** [pact-foundation/pact-stub-server#60]
While using 0.4.4 I'm able to run the server when a header key contains a "."  for example:
`"company.my-company-token" : "tokenValue"`

After that version every time I try to run the docker image 5.x.x i get the same error:

`ERROR main pact_stub_server:   - Failed to load pact file: Expected a "." or "[" instead of "'" in path expression "my-company-token']"`

Using keys with only - works fine, the issue seems to be with .

**Comment by rholshausen** [comment]
Can you provide the Pact file that has this issue?
