### ISSUE TITLE
Publish images to Github Container Registry

### ISSUE THREAD

**Issue by matanbaruch** [pact-foundation/pact-stub-server#61]
It would be nice to see pact-foundation in AWS Public Gallery
https://docs.aws.amazon.com/AmazonECR/latest/public/public-gallery.html

(Since Docker Hub limits are pain)

**Comment by YOU54F** [comment]
Hey hey,

I am not 100% sure if we have setup a dedicated AWS account for the Pact Org, will check.

Would publishing to GitHub `ghcr.io` help?

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by matanbaruch** [comment]
YES!

Since we are using it with Github Actions :)

**Comment by YOU54F** [comment]
Awesome, 

I assume it should be as simple as adding a CR_PAT (across the org, so we can reuse for our different repos as it makes sense to be consistent)

and then at the end of each existing publish step, we can just retag with `ghcr.io/<org>/<image>:<tag>

push and we are golden

**Comment by YOU54F** [comment]
What are the Docker limits and how many images are you pulling 😂 

Would love to hear more about your project, as I am sure others would in the community.

**Comment by matanbaruch** [comment]
We are using it in CI pipeline in Github Actions, The pact server is mocking our backend, so basically a lot!
We currently cloned it to our internal AWS ECR, but it would be nice to get latest releases and multi-arch builds.

**Comment by YOU54F** [comment]
Hey @matanbaruch,

Sorry this took so long! 

I've finally got a release out for you publishing to ghcr for the pact-stub-server, publishing to ghcr, and producing multi-arch arm/amd64 images. The binaries themselves are statically built with `musl` now so will work across musl and glibc based distros.

- [Action Run](https://github.com/pact-foundation/pact-stub-server/actions/runs/9034439839/job/24827509574)
- [Release](https://github.com/pact-foundation/pact-stub-server/releases/tag/v0.6.0)
- [DockerHub Image](https://hub.docker.com/r/pactfoundation/pact-stub-server)
- [GHCR Image](https://github.com/pact-foundation/pact-stub-server/pkgs/container/pact-stub-server)

I am tracking publishing all of our pact-foundation images to GHCR, which came out of the back of this request, so thank you

https://github.com/pact-foundation/devrel/issues/29
